version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd front
  pre_build:
    commands:
      - pip install --upgrade awscli
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build-dev
    post_build:
      commands:
        - echo Build completedd on `date`  
artifacts:
  files:
    - '**/*'
  base-directory: 'build'


