version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd front
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build-dev
    post_build:
      commands:
        - aws s3 sync front/build/ s3://sarthe-emploi-bucket/
        - echo Build completed on `date`  



